main: com.cynosure.FastTravel
name: FastTravel
version: 1.0-SNAPSHOT
api-version: 1.20.1

Commands:
  createpos:
    description: 注册一个导航点
    usage: /<command> [开始坐标组] [结束坐标组] [传送坐标组] [String:导航点名称] [String:父亲节点]
    permission-message: 你没有权限执行此指令
    permission: xxx
  deletepos:
    description: 删除一个导航点
    usage: /<command> [String:删除导航点的名称]
    permission-message: 你没有权限执行此指令
    permission: xxx
  travel:
    description: 启动快速旅行
    usage: /<command> [String:合法的导航点名称]
    permission: xxx
    permission-message: 你没有权限执行此指令
  travelGUI:
    description: 启动快速旅行GUI界面
    usage: /<command>
    permission: xxx
    permission-message: 你没有权限执行此指令
  travelPlayer:
    description: 为玩家启动旅行GUI
    usage: /<command> [player] [String:出发导航点名称]
    permission: xxx
    permission-message: 你没有权限执行此指令
